#!/bin/bash
sed '/<!DOCTYPE/,/Adopt<\/td>/d' |
sed '/<\/table>/,/<\/html>/d' |
sed '/<tr>/,/<\/td>/d' |
tr -d '\r\n' |
tr '[:upper:]' '[:lower:]' |
sed 's/<\/td>/\n/g' |
sed 's/\,/\n/g' |
sed s/\`/\'/g |
sed 's/<[^>]*>//g' | 
sed 's/ /\n/g' |
tr -d '[:blank:]' |
sed '/-/d' |
tr -cs "pk\'mnwlhaeiou" '[\n*]' |
sort -u |
sed '/^$/d'

